"""market schema

Revision ID: 1ccbeec3688d
Revises: 2ce115454594
Create Date: 2026-08-14 14:40:04.024874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ccbeec3688d'
down_revision: Union[str, None] = '2ce115454594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hot_videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('influencer_id', sa.String(length=36), nullable=True),
    sa.Column('influencer_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('plays', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('heat', sa.Float(), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('related_demand', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hot_videos_tenant_id'), 'hot_videos', ['tenant_id'], unique=False)
    op.create_table('influencers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('fans', sa.Integer(), nullable=False),
    sa.Column('avg_plays', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('interaction_rate', sa.Float(), nullable=False),
    sa.Column('verticality', sa.Float(), nullable=False),
    sa.Column('gmv', sa.Float(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('risk', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('suggestion', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('level_label', sa.String(length=120), nullable=True),
    sa.Column('fit_projects', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.String(length=120), nullable=True),
    sa.Column('competitors', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_tenant_id'), 'influencers', ['tenant_id'], unique=False)
    op.create_table('report_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('block', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_blocks_tenant_id'), 'report_blocks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_blocks_tenant_id'), table_name='report_blocks')
    op.drop_table('report_blocks')
    op.drop_index(op.f('ix_influencers_tenant_id'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_index(op.f('ix_hot_videos_tenant_id'), table_name='hot_videos')
    op.drop_table('hot_videos')
    # ### end Alembic commands ###

