"""instruction params

Revision ID: 336a23a8406b
Revises: e0bd29b5bf63
Create Date: 2026-08-14 17:39:16.069002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '336a23a8406b'
down_revision: Union[str, None] = 'e0bd29b5bf63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('params_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructions', 'params_json')
    # ### end Alembic commands ###

