"""linkstrate platform schema

Revision ID: 6f715272b1ab
Revises: 1ccbeec3688d
Create Date: 2026-08-14 15:17:57.020852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6f715272b1ab'
down_revision: Union[str, None] = '1ccbeec3688d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capabilities', sa.Column('price', sa.Integer(), server_default='0', nullable=False))
    op.add_column('capabilities', sa.Column('price_band', sa.String(length=64), nullable=True))
    op.add_column('capabilities', sa.Column('efficacy_json', sa.JSON(), nullable=True))
    op.add_column('capabilities', sa.Column('segments_json', sa.JSON(), nullable=True))
    op.add_column('capabilities', sa.Column('seasons_json', sa.JSON(), nullable=True))
    op.add_column('capabilities', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('capabilities', sa.Column('is_focus', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('demand_profiles', sa.Column('confidence', sa.Float(), server_default='0', nullable=False))
    op.add_column('demand_profiles', sa.Column('evidence', sa.Text(), nullable=True))
    op.add_column('demand_profiles', sa.Column('verified', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('demand_signals', sa.Column('segment', sa.String(length=64), nullable=True))
    op.add_column('strategies', sa.Column('status', sa.String(length=16), server_default='草稿', nullable=False))
    op.add_column('strategies', sa.Column('managed', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'managed')
    op.drop_column('strategies', 'status')
    op.drop_column('demand_signals', 'segment')
    op.drop_column('demand_profiles', 'verified')
    op.drop_column('demand_profiles', 'evidence')
    op.drop_column('demand_profiles', 'confidence')
    op.drop_column('capabilities', 'is_focus')
    op.drop_column('capabilities', 'description')
    op.drop_column('capabilities', 'seasons_json')
    op.drop_column('capabilities', 'segments_json')
    op.drop_column('capabilities', 'efficacy_json')
    op.drop_column('capabilities', 'price_band')
    op.drop_column('capabilities', 'price')
    # ### end Alembic commands ###

