"""multi industry base

Revision ID: 8b6efb19b1d0
Revises: 78d56681c456
Create Date: 2026-08-14 16:15:16.137149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b6efb19b1d0'
down_revision: Union[str, None] = '78d56681c456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('industry_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('industry_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_templates_industry_id'), 'industry_templates', ['industry_id'], unique=False)
    op.create_table('instructions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('industry_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('strategy_ids_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructions_tenant_id'), 'instructions', ['tenant_id'], unique=False)
    op.add_column('strategy_tasks', sa.Column('instruction_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_strategy_tasks_instruction_id'), 'strategy_tasks', ['instruction_id'], unique=False)
    op.add_column('tenants', sa.Column('industry_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_tenants_industry_id'), 'tenants', ['industry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_industry_id'), table_name='tenants')
    op.drop_column('tenants', 'industry_id')
    op.drop_index(op.f('ix_strategy_tasks_instruction_id'), table_name='strategy_tasks')
    op.drop_column('strategy_tasks', 'instruction_id')
    op.drop_index(op.f('ix_instructions_tenant_id'), table_name='instructions')
    op.drop_table('instructions')
    op.drop_index(op.f('ix_industry_templates_industry_id'), table_name='industry_templates')
    op.drop_table('industry_templates')
    op.drop_table('industries')
    # ### end Alembic commands ###

