"""strategy run cycle

Revision ID: 8f18eeadaad2
Revises: 6f715272b1ab
Create Date: 2026-08-14 15:34:53.564932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f18eeadaad2'
down_revision: Union[str, None] = '6f715272b1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('run_cycle', sa.Integer(), server_default='1440', nullable=False))
    op.add_column('strategies', sa.Column('last_run_at', sa.String(length=64), nullable=True))
    op.add_column('strategies', sa.Column('next_run_at', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'next_run_at')
    op.drop_column('strategies', 'last_run_at')
    op.drop_column('strategies', 'run_cycle')
    # ### end Alembic commands ###

