"""instruction asset

Revision ID: e0bd29b5bf63
Revises: 64a1640f062c
Create Date: 2026-08-14 17:19:55.161898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0bd29b5bf63'
down_revision: Union[str, None] = '64a1640f062c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('asset_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructions', 'asset_json')
    # ### end Alembic commands ###

